import type { Metadata } from "next";
import { Inter } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import { Providers } from "providers";
import { AppbarClient } from "components/AppbarClient";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      
      <body>
        <Providers>
        <div className=" min-w-screen min-h-screen bg-[#ebe6e6]">
       <AppbarClient/>
        {children}  
        </div>
         </Providers>
      </body>
     
    </html>
  );
}
